views.py


import mysql.connector

from flask import Flask, Blueprint, render_template, request, redirect, url_for, jsonify
from db import Database
from db_config import Config
from models import fetch_all_donors, fetch_blood_inventory
from functions import add_donation, update_blood_inventory
from functions import add_donor
import mysql.connector
from mysql.connector import Error

views = Blueprint('views', __name__)
app = Flask(__name__)


@views.route('/')
def index():
    return render_template('index.html')


@views.route('/donors')
def get_donors():
    db = Database()
    donors = fetch_all_donors(db)
    db.close()
    print(donors)  # Add this to debug the data
    return render_template('donors.html', donors=donors)


@views.route('/add_donor', methods=['POST', 'GET'])
def add_donors():
    if request.method == 'GET':
        # Render the template for the add donor form
        return render_template('add_donor.html')  # Ensure this points to your actual HTML file

    if request.method == 'POST':
        # Process form submission

        try:
            first_name = request.form['first_name']
            last_name = request.form['last_name']
            date_of_birth = request.form['date_of_birth']
            blood_type = request.form['blood_type']
            last_donated = request.form['last_donated']

            db = Database()
            add_donor(db, first_name, last_name, date_of_birth, blood_type, last_donated)
            db.close()

            return redirect(url_for('views.get_donors'))  # Adjust based on your setup

        except KeyError as e:
            # Handle missing fields gracefully
            return f"Missing field: {e}", 400


@views.route('/query_execute', methods=['GET'])
def query_execute():
    table_names = Config.get_table_names()
    return render_template('query_execute.html', table_names=table_names)


@views.route("/execute_query", methods=["POST"])
def execute_query():
    data = request.get_json()
    query = data.get("query")

    if not query:
        return jsonify({"error": "No query provided"}), 400

    try:
        connection = mysql.connector.connect(
            host=Config.DB_HOST,
            user=Config.DB_USER,
            password=Config.DB_PASSWORD,
            database=Config.DB_NAME,
        )
        cursor = connection.cursor()
        cursor.execute(query)

        # Fetch column names and rows
        if cursor.description:  # Check if the query returns rows
            columns = [col[0] for col in cursor.description]
            rows = cursor.fetchall()
            return jsonify({"columns": columns, "rows": rows})
        else:
            connection.commit()  # For queries like INSERT, UPDATE, DELETE
            return jsonify({"columns": [], "rows": [["Query executed successfully!"]]}), 200

    except Error as e:
        return jsonify({"error": str(e)}), 500
    finally:
        if 'connection' in locals() and connection.is_connected():
            cursor.close()
            connection.close()


@views.route('/blood-bank')
def get_blood_bank():
    db = Database()
    inventory = fetch_blood_inventory(db)
    db.close()
    return render_template('blood_bank.html', inventory=inventory)


@views.route('/donate', methods=['GET', 'POST'])
def donate_blood():
    if request.method == 'POST':
        donor_id = request.form['donor_id']
        donation_date = request.form['donation_date']
        donation_amount = request.form['donation_amount']
        blood_type = request.form['blood_type']

        db = Database()
        add_donation(db, donor_id, donation_date, donation_amount)
        update_blood_inventory(db, blood_type, 1)
        db.close()

        return redirect(url_for('views.get_blood_bank'))

    return render_template('donate.html')


@views.route('/get_columns/<table_name>', methods=['GET'])
def get_columns(table_name):
    try:
        # Connect to the database
        connection = mysql.connector.connect(
            host=Config.DB_HOST,
            user=Config.DB_USER,
            password=Config.DB_PASSWORD,
            database=Config.DB_NAME,
        )
        cursor = connection.cursor()
        cursor.execute(f"DESCRIBE {table_name}")
        columns = [row[0] for row in cursor.fetchall()]
        return jsonify(columns)
    except Exception as e:
        return jsonify({'error': str(e)}), 500
    finally:
        if 'connection' in locals() and connection.is_connected():
            connection.close()

templates/add_donor.html
{% extends "/index.html" %}
{% block content %}
    {{ donor }}
    <form action="{{ url_for('views.add_donors') if not donor else url_for('views.edit_donor', donor_id=donor['id']) }}"
          method="POST" class="max-w-sm mx-auto">
        <div class="mb-5">
            <label for="first_name" class="block mb-2 text-sm font-medium text-gray-900">First Name</label>
            <input type="text" id="first_name" name="first_name"
                   class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                   placeholder="Enter first name" required
                   value="{{ donor.first_name if donor else '' }}"/>
        </div>
        <div class="mb-5">
            <label for="last_name" class="block mb-2 text-sm font-medium text-gray-900">Last Name</label>
            <input type="text" id="last_name" name="last_name"
                   class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                   placeholder="Enter last name" required
                   value="{{ donor.last_name if donor else '' }}"/>
        </div>
        <div class="mb-5">
            <label for="date_of_birth" class="block mb-2 text-sm font-medium text-gray-900">Date of Birth</label>
            <input type="date" id="date_of_birth" name="date_of_birth"
                   class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                   required
                   value="{{ donor.date_of_birth if donor else '' }}"/>
        </div>
        <div class="mb-5">
            <label for="blood_type" class="block mb-2 text-sm font-medium text-gray-900">Blood Type</label>
            <select id="blood_type" name="blood_type"
                    class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                    required>
                <option value="" disabled {{ 'selected' if not donor else '' }}>Select blood type</option>
                <option value="A+" {{ 'selected' if donor and donor.blood_type == 'A+' else '' }}>A+</option>
                <option value="A-" {{ 'selected' if donor and donor.blood_type == 'A-' else '' }}>A-</option>
                <option value="B+" {{ 'selected' if donor and donor.blood_type == 'B+' else '' }}>B+</option>
                <option value="B-" {{ 'selected' if donor and donor.blood_type == 'B-' else '' }}>B-</option>
                <option value="O+" {{ 'selected' if donor and donor.blood_type == 'O+' else '' }}>O+</option>
                <option value="O-" {{ 'selected' if donor and donor.blood_type == 'O-' else '' }}>O-</option>
                <option value="AB+" {{ 'selected' if donor and donor.blood_type == 'AB+' else '' }}>AB+</option>
                <option value="AB-" {{ 'selected' if donor and donor.blood_type == 'AB-' else '' }}>AB-</option>
            </select>
        </div>
        <div class="mb-5">
            <label for="last_donated" class="block mb-2 text-sm font-medium text-gray-900">Last Donated Date</label>
            <input type="date" id="last_donated" name="last_donated"
                   class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
                   value="{{ donor.last_donated if donor else '' }}"/>
        </div>
        <button type="submit"
                class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">
            {{ 'Edit Donor' if donor else 'Add Donor' }}
        </button>
    </form>
{% endblock %}

templates/donors.html
{% extends "/index.html" %}

{% block content %}

{#    {{ donors }}#}
    <div class="relative overflow-x-auto shadow-md">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 ">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50  ">
            <tr>
                <th scope="col" class="px-8 py-3">
                    Full Name
                </th>
                <th scope="col" class="px-6 py-3">
                    <div class="flex items-center">
                        Date of Birth
                        <a href="#">
                            <svg class="w-3 h-3 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                 fill="currentColor" viewBox="0 0 24 24">
                                <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                            </svg>
                        </a>
                    </div>
                </th>
                <th scope="col" class="px-6 py-3">
                    <div class="flex items-center">
                        Blood type
                        <a href="#">
                            <svg class="w-3 h-3 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                 fill="currentColor" viewBox="0 0 24 24">
                                <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                            </svg>
                        </a>
                    </div>
                </th>


                <th scope="col" class="px-6 py-3">
                    <div class="flex items-center">
                        Phone Number
                        <a href="#">
                            <svg class="w-3 h-3 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                 fill="currentColor" viewBox="0 0 24 24">
                                <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                            </svg>
                        </a>
                    </div>
                </th>
                <th scope="col" class="px-2 py-3">
                    <div class="flex items-center">
                        Last Donated
                        <a href="#">
                            <svg class="w-3 h-3 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                                 fill="currentColor" viewBox="0 0 24 24">
                                <path d="M8.574 11.024h6.852a2.075 2.075 0 0 0 1.847-1.086 1.9 1.9 0 0 0-.11-1.986L13.736 2.9a2.122 2.122 0 0 0-3.472 0L6.837 7.952a1.9 1.9 0 0 0-.11 1.986 2.074 2.074 0 0 0 1.847 1.086Zm6.852 1.952H8.574a2.072 2.072 0 0 0-1.847 1.087 1.9 1.9 0 0 0 .11 1.985l3.426 5.05a2.123 2.123 0 0 0 3.472 0l3.427-5.05a1.9 1.9 0 0 0 .11-1.985 2.074 2.074 0 0 0-1.846-1.087Z"/>
                            </svg>
                        </a>
                    </div>
                </th>
                <th scope="col" class="px-1 py-3">
                    <span class="sr-only">Edit</span>
                </th>

            </tr>
            </thead>
            <tbody>
            <tr class="bg-white border-b ">
                {% for donor in donors %}
                    <td class="px-6 py-4">
                        {% set full_name = donor.first_name + " " + donor.last_name %}
                        {{ full_name }}
                    </td>
                    <td class="px-6 py-4">

                        {{ donor.date_of_birth }}
                    </td>
                    <td class="px-6 py-4">
                        {{ donor.blood_type }}
                    </td>
                    <td class="px-6 py-4">
                        {% if donor.contact_number %}
                            {{ donor.contact_number }}
                        {% else %}
                            Not Provided
                        {% endif %}
                    </td>
                    <td class="px-6 py-4 ">
                        {% if donor.last_donated %}
                            {{ donor.last_donated }}

                        {% else %}
                            Not Provided
                        {% endif %}
                    </td>
                    <td class="px-1 py-4 text-center space-x-3">
                        <a href="/add_donor?donor_id={{ donor.donor_id }}" class="font-medium text-blue-600">Edit</a>
                        <a href="#" class="font-medium text-blue-600">Delete</a>
                    </td>
                {% endfor %}
            </tr>

            </tbody>
        </table>
    </div>

{% endblock %}

templates/index.html
{% extends "/base/base.html" %}

templates/query_execute.html
{% extends "index.html" %}
{% block content %}
    <div class="container mx-auto max-w-4xl gap-4">
        <!-- Query Input Section -->
        <div>
            <label for="query-input" class="block mb-2 text-sm font-medium text-gray-900">Put Your Query Here</label>
            <textarea id="query-input" rows="4"
                      class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="Write your thoughts here..."></textarea>
        </div>

        <!-- Submit Button -->
        <button type="button" id="execute-query"
                class="mt-2 text-white bg-blue-500 hover:bg-blue-700 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 focus:outline-none">
            Submit Query
        </button>

        <div class="grid grid-cols-2 mt-6">
            <div>
                <h2 class="mb-2 text-lg font-semibold text-gray-900">Existing Tables</h2>
                <ul class="max-w-md space-y-2 text-gray-400 list-inside">
                    {% for table in table_names %}
                        <li>
                            <button type="button" id="{{ table }}"
                                    class="table-btn py-2.5 px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100">
                                {{ table }}
                            </button>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div>
                <label for="columns" class="block mb-2 text-sm font-medium text-gray-900">Columns of Selected
                    Table</label>
                <textarea id="columns" rows="8"
                          class="block p-2.5 w-full text-sm text-gray-900 bg-gray-100 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500"
                          readonly></textarea>
            </div>
        </div>

        <!-- Result Table Section -->
        <div id="query-result" class="mt-6">
            <!-- The resulting table will be inserted here by JS -->
        </div>
    </div>


    <script src="../static/js/get_columns.js" type="text/javascript"></script>
    <script src="../static/js/query_handler.js" type="text/javascript"></script>
{% endblock %}

{#    <script src="{{ url_for('static', filename='js/get_columns.js') }}"></script>#}